SEIRD vignette following Lisa's comments
Como-DTC-Collaboration/como-models pull request #38
Opened 2021-11-11 10:33 UTC by FarmHJ

- Included more description on the conditions when the model can be used
- Renamed S_0, E_0, I_0, R_0... to S_{init}, E_{init}, I_{init}, R_{init} in the vignette to avoid confusion of R_0 as initial value of R and reproductive number. 
- Expressed incidences as cases per 1000 of the population instead of fraction of population

2021-12-10 15:17 UTC, rcw5890 requested changes

2021-12-10 15:17 UTC, rcw5890 commented on vignettes/SEIRD.Rmd
> +The full SEIRD model consists of four ODEs that a coupled together: the first of these governs the behaviour of susceptible individuals, which has already been introduced. The next equation governs t
```suggestion
The full SEIRD model consists of four ODEs that are coupled together: the first of these governs the behaviour of susceptible individuals, which has already been introduced. The next equation governs the growth of the exposed compartment:
```

2021-12-10 15:17 UTC, rcw5890 commented on vignettes/SEIRD.Rmd
> +An alternative way to view these exponential decay curves is as probability distributions governing the time taken for an exposed individual to become infectious. This period is referred to as the la
I think this paragraph needs 1--2 sentences extra explanation---some readers may be confused that we are suddenly talking about probability distributions and a mean in the deterministic model.

2021-12-10 15:17 UTC, rcw5890 commented on vignettes/SEIRD.Rmd
> +So the equilbria are given by $S=S'$, $E=0$, and $I=0$ which corresponds to a situation when there are no infected or infectious individuals in the population. In other words, in this model, there is
```suggestion
So the equilibria are given by $S=S'$, $E=0$, and $I=0$ which corresponds to a situation when there are no infected or infectious individuals in the population. In other words, in this model, there is no endemic equilibrium when the infection remains present throughout the population; only epidemic dynamics are possible.
```

2021-12-10 15:17 UTC, rcw5890 commented on vignettes/SEIRD.Rmd
> +This is can be explored through the basic reproductive number, $R_0$, which is the expected number of people infected by a single infectious individual in a population where everyone is susceptible.
```suggestion
This is can be explored through the basic reproductive number, $R_0$, which is the expected number of people infected by a single infectious individual in a population where everyone is susceptible. (Note that this basic reproductive number is unrelated to the initial condition for the recovered population.) 
```

2021-12-10 17:19 UTC, ben18785 commented on vignettes/SEIRD.Rmd
> +An alternative way to view these exponential decay curves is as probability distributions governing the time taken for an exposed individual to become infectious. This period is referred to as the la
Thanks Richard. I've changed this now.

2021-12-12 11:26 UTC, ben18785 commented
Closing as is now being covered in #46

2021-12-12 11:26 UTC, closed without merging