SEIRDAge + its vignette changes
Como-DTC-Collaboration/como-models pull request #46
Opened 2021-12-11 17:56 UTC by ben18785

- Makes the vignette more pedagogical and justifies the choices of parameters used in the simulation
- Adds an R0 calculator for the method
- Allows age-specific recovery rates #45 
- Corrects documentation error #43

2021-12-16 12:38 UTC, oscardm20994 requested changes
Looking in good shape!

have provided some in-line comments which are mostly grammar/clarifications of explanations of a few points. The only technical point I saw was the potential naming problem with R0 used to both define the initial number of recovered population (a slot in the SEIRD and SEIRDAge s4 classes) and the R0 number. This may be my general misunderstanding of how the R0 number is calculated and might be a non-issue but thought it was worth mentioning. 

Other than that, looks good!

2021-12-16 12:38 UTC, oscardm20994 commented on R/SEIRDAge.R
> +#' mu can and recovery rate g either be a single number, in which case all ages
delete 'can' in this line

2021-12-16 12:38 UTC, oscardm20994 commented on R/SEIRDAge.R
> +#' mu can and recovery rate g either be a single number, in which case all ages
parameters b, and k are numbers. The death rate, mu, and recovery rate, g, can either be a single number, in which case all ages

2021-12-16 12:38 UTC, oscardm20994 commented on R/SEIRDAge.R
> +#' Here b is the rate of infection; k is the rate of transitioning from the
might be worth mentioning which compartments this rate of transitioning involves (E to I etc)

2021-12-16 12:38 UTC, oscardm20994 commented on R/SEIRDAge.R
> +#' G, where G_ij gives the expected number of secondary infections of type i
unsure of the significance of 'secondary' here. this may just be me not understanding how R0 is properly calculated but may be worth clarifying.

2021-12-16 12:38 UTC, oscardm20994 commented on man/SEIRDAge-class.Rd
> +mu can and recovery rate g either be a single number, in which case all ages
shuffle this sentence around as in the SEIRDAge file

2021-12-16 12:38 UTC, oscardm20994 commented on tests/testthat/test_SEIRDAge.R
> +})
Is there not a potential naming problem here with R0 (the initial number of recovered population) and the R number which is also denoted R0? 

I'm not sure which one this is testing?

again, I may be misunderstanding the meaning of the R number.

2021-12-16 12:38 UTC, oscardm20994 commented on vignettes/SEIRD.Rmd
> +For all models in this packages, it is assumed that the population size is sufficiently large that we can view the number of individuals in a given compartment on a continuous scale. We also assume t
in this package

2021-12-16 12:38 UTC, oscardm20994 commented on vignettes/SEIRD.Rmd
> +Using repeatedly sampled PCR test data from close contacts of confirmed cases in mainland China, a recent study estimated the latency period of COVID-19 as 5.51 days and a log-normal probability dist
does this study refer to xin2021? or our study?

2021-12-16 12:38 UTC, oscardm20994 commented on vignettes/SEIRD.Rmd
> +We note that natural births and deaths -- in other words, those unrelated to infection -- are not considered in this model. Therefore, the SEIRD model is suitable only to  diseases that span a short
maybe be more specific and say that the 'natural' births and deaths do not significantly affect the stock of susceptibles as this is the compartment they are likely to influence the most.

2021-12-16 12:38 UTC, oscardm20994 commented on vignettes/SEIRD.Rmd
> +  R0(model)
again, possible issue with a function called R0 as well as a class slot with the same name? may be fine but possibly best to change

2021-12-16 12:38 UTC, oscardm20994 commented on vignettes/SEIRD_age_structured.Rmd
> +The basic SEIRD model assumes that individuals with the same infection status behave identically and that the infection has the same effect. In reality, however, individuals with the same infection s
could we provide a link back to the SEIRD vignette? In case a user opens this one first and would like to access the simpler model.

2021-12-22 16:28 UTC, ben18785 commented on R/SEIRDAge.R
> +#' Here b is the rate of infection; k is the rate of transitioning from the
Good idea. Done.

2021-12-22 16:29 UTC, ben18785 commented on R/SEIRDAge.R
> +#' G, where G_ij gives the expected number of secondary infections of type i
I've removed secondary.

2021-12-22 16:30 UTC, ben18785 commented on tests/testthat/test_SEIRDAge.R
> +})
I don't think so, personally. I think this distinction is almost always clear and this terminology is used in the literature. We can always revisit later if we think it's difficult to parse.

2021-12-22 16:33 UTC, ben18785 commented on vignettes/SEIRD.Rmd
> +We note that natural births and deaths -- in other words, those unrelated to infection -- are not considered in this model. Therefore, the SEIRD model is suitable only to  diseases that span a short
Good idea. Done.

2021-12-22 16:37 UTC, ben18785 commented on vignettes/SEIRD_age_structured.Rmd
> +The basic SEIRD model assumes that individuals with the same infection status behave identically and that the infection has the same effect. In reality, however, individuals with the same infection s
Great idea. I've linked back to the markdown file. We can change this to be rendered version of the document once we figure out how to host stuff.

2021-12-22 17:56 UTC, merged